name: Docker CI/CD

on:
  push:
    branches:
      - main
      - devakash

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/myappaugust

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only deploy from main
    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }} # set this secret to ubuntu OR ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/myappaugust:latest"

            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            docker pull "$IMAGE" || true
            docker rm -f myappaugust || true

            # Nginx serves on 80 inside container; map it to 3000 outside
            docker run -d --name myappaugust \
              -p 3000:80 \
              --restart=always "$IMAGE"

            docker ps --filter "name=myappaugust" --format "table {{.Names}}\t{{.Image}}\t{{.Ports}}\t{{.Status}}"
                          # --restart=always "$IMAGE"
