name: Docker CI/CD

on:
  push:
    branches: [main, devakash]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/myappaugust

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/myappaugust:latest"

            # Login to Docker Hub (needed if private repo)
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # Pull latest image
            docker pull "$IMAGE" || true

            # Stop and remove old container
            docker rm -f }/myappaugust || true

            # Run new container
            docker run -d --name /myappaugust -p 3000:3000 -p 3001:3001 --restart=always "$IMAGE"

            # Show running containers
            docker ps --filter "name=/myappaugust"

# testing my CI CD are working or not
# testing my CI CD are working or not
